apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-keycloak

resources:
  - ../../base

secretGenerator:
- name: keycloak-secret
  envs:
  - keycloak.env

patches:
  - target:
      kind: Service
      name: keycloak
    path: svc-patch.yaml

