apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-system-manager

resources:
  - ../../base

configMapGenerator:
  - name: system-manager-web-config
    files:
      - .env=system-manager-web.env
    behavior: create

patches:
  - path: svc-patch.yaml
    target:
      version: v1
      kind: Service
      name: system-manager-web
