apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-embed-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-embed-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0         
  template:
    metadata:
      labels:
        app: fast-embed-server
    spec:
      containers:
        - name: fast-embed-server
          image: ccr.ccs.tencentyun.com/megalab/fast-embed-service
          env:
            - name: APP_NAME
              value: "fast-embed-server"
            - name: APP_PORT
              value: "80"
          resources:
            requests:
              memory: "4Gi"   
            limits:
              memory: "4Gi"                
          ports:
            - containerPort: 80