apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-manager-web
  labels:
    app: system-manager-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-manager-web
  template:
    metadata:
      labels:
        app: system-manager-web
    spec: 
      containers:
      - name: system-manager-web
        image: ccr.ccs.tencentyun.com/megalab/system-manager-web
        ports:
          - containerPort: 3000               
        volumeMounts:
          - name: config-volume
            mountPath: /app/.env
            subPath: .env
            readOnly: true
          - mountPath: /etc/localtime
            name: localtime
            readOnly: true              
      volumes:
        - name: config-volume
          configMap:
            name: system-manager-web-config
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File                     