apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-ops-pilot

resources:
  - ../../base

configMapGenerator:
  - name: munchkin-web-config
    files:
      - .env=munchkin-web.env
    behavior: create

patches:
  - path: svc-patch.yaml
    target:
      version: v1
      kind: Service
      name: munchkin-web


