apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-system-manager

resources:
  - ../../base

configMapGenerator:
  - name: nats-config
    files:
      - nats-server.conf=nats-server.conf