apiVersion: apps/v1
kind: Deployment
metadata:
  name: bce-embed-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bce-embed-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0        
  template:
    metadata:
      labels:
        app: bce-embed-server
    spec:
      containers:
        - name: bce-embed-server
          image: ccr.ccs.tencentyun.com/megalab/bce-embed-service
          env:
            - name: APP_NAME
              value: "bce-embed-server"
            - name: APP_PORT
              value: "80"
          resources:
            requests:
              memory: "4Gi"   
            limits:
              memory: "4Gi"  
          ports:
            - containerPort: 80
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "curl -s --max-time 2 http://127.0.0.1:80 > /dev/null"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "curl -s --max-time 2 http://127.0.0.1:80 > /dev/null"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3            