apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app: nats
  type: NodePort
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222
      name: tcp-4222
      nodePort: 4222
    - protocol: TCP
      port: 8222
      targetPort: 8222
      name: tcp-8222
    - protocol: TCP
      port: 6222
      targetPort: 6222
      name: tcp-6222
