apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:   
      containers:
      - name: keycloak
        image: ccr.ccs.tencentyun.com/megalab/keycloak:26.1.0
        args:
          - "start"
        env:
          - name: KC_DB
            value: "postgres"
          - name: KC_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KC_HOSTNAME
          - name: KC_DB_URL
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KC_DB_URL
          - name: KC_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KC_DB_USERNAME   
          - name: KC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KC_DB_PASSWORD
          - name: KC_BOOTSTRAP_ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KC_BOOTSTRAP_ADMIN_USERNAME
          - name: KC_BOOTSTRAP_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KC_BOOTSTRAP_ADMIN_PASSWORD
          - name: KC_PROXY_HEADERS
            value: "forwarded"             
          - name: KC_HOSTNAME_STRICT
            value: "false"
          - name: KC_HTTP_ENABLED
            value: "true"
          - name: JAVA_OPTS
            value: "-Xms2g -Xmx4g"     

        volumeMounts:
          - mountPath: /etc/localtime
            name: localtime
            readOnly: true

      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File