apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-manager-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-manager-app
  template:
    metadata:
      labels:
        app: system-manager-app
    spec:
      containers:
        - name: system-manager-app
          image: ccr.ccs.tencentyun.com/megalab/system-manager
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: system-manager-config
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
