apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-manager-app
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-keycloak
          image: curlimages/curl:latest
          command: ['sh']
          args:
            - -c
            - >
              until curl -s -o /dev/null -w "%{http_code}" $KEYCLOAK_URL_API | grep -q "302"; do
                echo "Waiting for Keycloak to be ready...";
                sleep 5;
              done
          env:
            - name: KEYCLOAK_URL_API
              valueFrom:
                configMapKeyRef:
                  name: system-manager-config
                  key: KEYCLOAK_URL_API
        - name: wait-for-postgres
          image: postgres:15
          command: ['sh']
          args:
            - -c
            - >
              until pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER; do
                echo "Waiting for PostgreSQL to be ready...";
                sleep 2;
              done
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-manager-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-manager-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: system-manager-config
                  key: DB_USER
        - name: init-keycloak
          image: ccr.ccs.tencentyun.com/megalab/system-manager
          command: ['sh']
          args:
            - -c
            - >
              python manage.py init_realm &&
              python manage.py init_realm_resource
          envFrom:
            - configMapRef:
                name: system-manager-config
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
