apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-system-manager

resources:
  - ../../base

configMapGenerator:
  - name: system-manager-config
    envs:
      - system-manager.env
    behavior: create

patches:
  - path: deploy-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: system-manager-app