apiVersion: apps/v1
kind: Deployment
metadata:
  name: munchkin-web
  labels:
    app: munchkin-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  selector:
    matchLabels:
      app: munchkin-web
  template:
    metadata:
      labels:
        app: munchkin-web
    spec: 
      containers:
      - name: munchkin-web
        image: ccr.ccs.tencentyun.com/megalab/opspilot-web
        ports:
          - containerPort: 3000               
        volumeMounts:
          - name: config-volume
            mountPath: /app/.env
            subPath: .env
            readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: munchkin-web-config