apiVersion: apps/v1
kind: Deployment
metadata:
  name: opspilot-app
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15
          command: ['sh']
          args:
            - -c
            - >
              until pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER; do
                echo "Waiting for PostgreSQL to be ready...";
                sleep 2;
              done
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: opspilot-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: opspilot-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: opspilot-config
                  key: DB_USER
