apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-ops-pilot

resources:
  - ../../base

configMapGenerator:
  - name: opspilot-config
    envs:
      - munchkin.env
    behavior: create

patches:
  - path: deploy-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: opspilot-app