apiVersion: apps/v1
kind: Deployment
metadata:
  name: chunk-server
  namespace: lite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chunk-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0      
  template:
    metadata:
      labels:
        app: chunk-server
    spec:
      containers:
        - name: chunk-server
          image: ccr.ccs.tencentyun.com/megalab/chunk-service
          env:
            - name: APP_NAME
              value: "chunk-server"
            - name: APP_PORT
              value: "80"
          ports:
            - containerPort: 80