apiVersion: apps/v1
kind: Deployment
metadata:
  name: opspilot-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: opspilot-app
  template:
    metadata:
      labels:
        app: opspilot-app
    spec:
      containers:
        - name: opspilot-app
          image: ccr.ccs.tencentyun.com/megalab/opspilot
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: opspilot-config
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
          resources:
            requests:
              memory: "4Gi"   
            limits:
              memory: "4Gi"   
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "curl -s --max-time 2 http://127.0.0.1:8000 > /dev/null"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "curl -s --max-time 2 http://127.0.0.1:8000 > /dev/null"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3                              
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
            
