apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server
  namespace: lite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: chat-server
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: "node-role.kubernetes.io/control-plane"
      #               operator: NotIn
      #               values:
      #                 - "true"    
      containers:
        - name: chat-server
          image: ccr.ccs.tencentyun.com/megalab/chat-service
          env:
            - name: APP_NAME
              value: "chat-server"
            - name: APP_PORT
              value: "80"
          ports:
            - containerPort: 80