apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-service
  template:
    metadata:
      labels:
        app: kube-service
    spec:
      serviceAccountName: kube-client-sa
      containers:
        - name: kube-service
          image: ccr.ccs.tencentyun.com/megalab/kube-service
          env:
            - name: APP_NAME
              value: "kube-service"
            - name: APP_PORT
              value: "80"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: kube-service-secret
                  key: TOKEN     
          ports:
            - containerPort: 80