apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-ops-pilot

resources:
  - ../../base

patches:
  - path: svc-patch.yaml
    target:
      version: v1
      kind: Service
      name: fast-embed-server     

