apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-ops-pilot

resources:
  - ../../base

secretGenerator:
- name: minio-secret
  envs:
    - minio.env

patches:
  - path: sts-patch.yaml
    target: 
      group: apps
      version: v1
      kind: StatefulSet
      name: minio
  - path: svc-patch.yaml
    target:
      version: v1
      kind: Service
      name: minio