apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0      
  template:
    metadata:
      labels:
        app: rag-server
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: "node-role.kubernetes.io/control-plane"
      #               operator: NotIn
      #               values:
      #                 - "true"    
      containers:
        - name: rag-server
          image: ccr.ccs.tencentyun.com/megalab/rag-service
          env:
            - name: APP_NAME
              value: "rag-server"
            - name: APP_PORT
              value: "80"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: memory-volume
              mountPath: /memory
      volumes:
        - name: memory-volume
          persistentVolumeClaim:
            claimName: rag-server-memory