apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-ops-pilot

resources:
  - ../../base

secretGenerator:
- name: postgres-secret
  envs: 
  - postgres.env

patches:
  - path: sts-patch.yaml
    target: 
      group: apps
      version: v1
      kind: StatefulSet
      name: postgres