apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-server
  template:
    metadata:
      labels:
        app: ocr-server
    spec:
      containers:
        - name: ocr-server
          image: ccr.ccs.tencentyun.com/megalab/ocr-service
          env:
            - name: APP_NAME
              value: "ocr-server"
            - name: APP_PORT
              value: "80"
            - name: ENABLE_AZURE_OCR
              value: "True"
            - name: AZURE_OCR_ENDPOINT
              value: "https://megalab-vision.cognitiveservices.azure.com/"
            - name: AZURE_OCR_KEY
              value: "2d8bb73ff5ab47fdaca873fa2ee515fd"
          resources:
            requests:
              memory: "6Gi"   
            limits:
              memory: "6Gi"
          ports:
            - containerPort: 80